namespace: traefik
helm:
  releaseName: traefik
  repo: https://traefik.github.io/charts
  chart: traefik
  values:
    service:
      type: NodePort
    ports:
      web:
        nodePort: 32080
      websecure:
        nodePort: 32443