apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
data:
  POSTGRES_USER: a2V5Y2xvYWs=  # "keycloak" encoded in base64
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ=  # "secretpassword" encoded in base64
  POSTGRES_DB: a2V5Y2xvYWs=  # "keycloak" encoded in base64