apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
data:
  username: a2V5Y2xvYWs=  # base64 for "keycloak"
  password: c2VjcmV0cGFzc3dvcmQ=  # base64 for "secretpassword"
  database: a2V5Y2xvYWs=  # base64 for "keycloak"