apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: database
type: Opaque
data:
  postgres-password: c2VjcmV0cGFzc3dvcmQ=  # "secretpassword" base64 encoded
  username: a2V5Y2xvYWs=  # "keycloak" base64 encoded
  database: a2V5Y2xvYWs=  # "keycloak" base64 encoded