apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: auth
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`keycloak.local`)
      kind: Rule
      services:
        - name: keycloak-http
          port: 80