replicas: 1
postgresql:
  enabled: false
externalDatabase:
  host: postgresql.database.svc.cluster.local
  port: 5432
  database: keycloak
  username: keycloak
  password: secretpassword
service:
  type: NodePort
  ports:
    http: 
      nodePort: 32090
    https:
      nodePort: 32443
ingress:
  enabled: false