apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.0.1
    valuesFile: values.yaml