apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
helmCharts:
  - name: keycloak
    repo: https://charts.bitnami.com/bitnami
    version: 16.1.0
    valuesFile: values.yaml