postgresql:
  enabled: false

externalDatabase:
  host: postgresql.database.svc.cluster.local
  user: keycloak
  password: secretpassword
  database: keycloak

service:
  type: ClusterIP
  ports:
    http: 8080